[build]
  base = "/opt/build/repo/studio"
  command = "npm ci && npm run build"
  publish = "/opt/build/repo/studio/studio/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

